#!/bin/bash

case "$1" in
  start | reload | up)
    docker compose up -d
    ;;
  stop | down)
    docker compose down
    ;;
  reboot | restart)
    docker compose down
    docker compose up -d
    ;;
  rebuild)
    docker compose down
    docker compose build --no-cache --pull $@
    docker compose up -d
    ;;
  cli)
    docker exec -it Core bash -c "sudo -u devuser /bin/bash"
    ;;
  lzd)
    docker exec -it SERVER_TOOLS lazydocker
    ;;
  *)
    docker exec -it Core $@
    ;;
esac
